PRAGMA foreign_keys = ON;

-- Cree aqui las tablas del modelo CineMax.
-- Recuerde usar maximo 4 tablas e incluir:
-- PRIMARY KEY, FOREIGN KEY, NOT NULL, UNIQUE y CHECK.

CREATE TABLE Peliculas (
    ID_PELICULA INTEGER PRIMARY KEY,
    TITULO TEXT NOT NULL UNIQUE,
    DURACION INTEGER NOT NULL CHECK( DURACION > 0),
    GENERO TEXT,
    CLASIFICACION TEXT
);
CREATE TABLE Sala_Proyeccion(
    ID_SALA INTEGER PRIMARY KEY,
    NOMBRE_SALA  TEXT NOT NULL,
    CAPACIDAD_ASIENTOS INTEGER
);

CREATE TABLE Funcion(
    ID_FUNCION  INTEGER PRIMARY KEY,
    ID_PELICULA INTEGER,
    ID_SALA INTEGER NOT NULL,
    FECHA  TEXT NOT NULL,
    HORA TIME NOT NULL,
    PRECIO_BOLETO DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (ID_PELICULA) REFERENCES  Peliculas(ID_PELICULA),
    FOREIGN KEY (ID_SALA) REFERENCES Sala_Proyeccion(ID_SALA)
);
CREATE TABLE Boleto (
    ID_BOLETO INTEGER PRIMARY KEY,
    ID_FUNCION INTEGER,
    FECHA_VENTA TEXT NOT NULL,
    NUMERO_ASIENTO INTEGER,
    TOTAL_PAGO DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (ID_FUNCION) REFERENCES Funcion(ID_FUNCION)
);
